### ISSUE TITLE
0.01 Roadmap

### ISSUE THREAD

**Issue by leigh-johnson** [Nuwen/patch-it#7]
## Site-wide
- [x] Responsive grid, specify behavior @ xs, sm, md viewports
## User & Account System
- [x] Basic auth & access policies
- [ ] Project-based roles.
- [ ] Role-based privileges (editing, new, deleting, etc)
- [ ] LDAP integration (wishlist)
- [ ] OAUTH token system (Jira connection)
## Test Execution
- [ ] Allow users to "join" 2+ player tests
- [ ] pub/sub patterns on each suite instance
- [ ] Create a Jira bug
- [ ] Associate existing/created bug, sub to changes over Oauth connection
## Project System
- [x] template, platform, device associations
- [x] blueprint query models
## Notification System
- [ ] Alert users to % remaining test tasks, new tasks, new versions
- [ ] Flag test tasks associated with actioned Jira task
## Template System
- [x] Create/clone a template
- [x] Edit existing template
## Device System
- [ ] Upload device info
## Platform system
- [ ] Create/edit/delete platforms, associate per-project
